#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
ENV_FILE=${1:-$ROOT/configs/mbp-rpc/service-chain.env.example}

if [[ ! -f "$ENV_FILE" ]]; then
  echo "env file not found: $ENV_FILE" >&2
  exit 1
fi

set -a
source "$ENV_FILE"
set +a

: "${KAIA_INSTALL_DIR:?missing KAIA_INSTALL_DIR}"
: "${KAIA_DATA_DIR:?missing KAIA_DATA_DIR}"
: "${KAIA_LOG_DIR:?missing KAIA_LOG_DIR}"
: "${NETWORK_ID:?missing NETWORK_ID}"
: "${P2P_PORT:?missing P2P_PORT}"
: "${RPC_PORT:?missing RPC_PORT}"
: "${WS_PORT:?missing WS_PORT}"
: "${RPC_ADDR:?missing RPC_ADDR}"
: "${WS_ADDR:?missing WS_ADDR}"
: "${RPC_VHOSTS:=*}"
: "${RPC_CORSDOMAIN:=*}"
: "${WS_ORIGINS:=*}"
: "${RPC_API:?missing RPC_API}"
: "${WS_API:?missing WS_API}"

OUT=${2:-$ROOT/build/mbp-rpc/ksend.conf}
mkdir -p "$(dirname "$OUT")"

ADDITIONAL_ARGS=""
if [[ "${ENABLE_DEBUG:-0}" == "1" ]]; then
  ADDITIONAL_ARGS='ADDITIONAL="$ADDITIONAL --rpc.unsafe-debug.disable"'
fi

cat > "$OUT" <<CONF
# Generated by scripts/render-kaia-service-rpc-conf.sh
NETWORK=
NETWORK_ID=${NETWORK_ID}
PORT=${P2P_PORT}
SERVER_TYPE="fasthttp"
SYNCMODE="full"
VERBOSITY=3
MAXCONNECTIONS=100
DATA_DIR=${KAIA_DATA_DIR}
LOG_DIR=${KAIA_LOG_DIR}
RPC_ENABLE=1
RPC_API="${RPC_API}"
RPC_ADDR="${RPC_ADDR}"
RPC_PORT=${RPC_PORT}
RPC_VHOSTS="${RPC_VHOSTS}"
RPC_CORSDOMAIN="${RPC_CORSDOMAIN}"
WS_ENABLE=1
WS_API="${WS_API}"
WS_ADDR="${WS_ADDR}"
WS_PORT=${WS_PORT}
WS_ORIGINS="${WS_ORIGINS}"
TXPOOL_EXEC_SLOTS_ALL=16384
TXPOOL_NONEXEC_SLOTS_ALL=16384
TXPOOL_EXEC_SLOTS_ACCOUNT=16384
TXPOOL_NONEXEC_SLOTS_ACCOUNT=16384
${ADDITIONAL_ARGS}
CONF

echo "$OUT"
